selected_scheme scheme-minimal
TEXDIR /usr/local/texlive/2017
TEXMFCONFIG ~/.texlive2017/texmf-config
TEXMFHOME ~/texmf
TEXMFLOCAL /usr/local/texlive/texmf-local
TEXMFSYSCONFIG /usr/local/texlive/2017/texmf-config
TEXMFSYSVAR /usr/local/texlive/2017/texmf-var
TEXMFVAR ~/.texlive2017/texmf-var
binary_x86_64-linux 1
collection-basic 1
in_place 0
option_adjustrepo 1
option_autobackup 1
option_backupdir tlpkg/backups
option_desktop_integration 1
option_doc 0
option_file_assocs 1
option_fmt 1
option_letter 0
option_menu_integration 1
option_path 1
option_post_code 1
option_src 0
option_sys_bin /usr/local/bin
option_sys_info /usr/local/info
option_sys_man /usr/local/man
option_w32_multi_user 1
option_write18_restricted 1
portable 0
